### ISSUE TITLE
Input for GLIMPSE

### ISSUE THREAD

**Issue by SharkoTools** [hringbauer/ancIBD#3] opened 2023-03-27 08:34 UTC
Hello!

In the bioarchive article, you write that you are using data from the AADR, but there they are in the eigenstrat format. Tell me how to translate them into VCF with the flag of GL. And how, then, is the difference between capture and  whole genome data? Or do you have a BAM file for the 1240k panel?

**Comment by hringbauer** [comment] 2023-03-27 11:13
Hi @SharkoTools!

ancIBD cannot start from "eigenstrat" data as they contain only pseudo-haploid data and it is impossible to get the GL out of it.

We started everything from the original  .bam files - for the public AADR these are publicly available as listed in the respective publications. 

Collecting all of them is a laborious task, you could start by downloading big publications of most interest to you.

**Comment by hringbauer** [comment] 2023-04-12 12:38
Closing this "issue" (is a usage question, no bug fix needed).

**Comment by hringbauer** [comment] 2023-04-12 12:39
Closing this "issue" (is a usage question, not a bug report that needs action).

**Comment by hringbauer** [comment] 2023-04-12 12:39
Closing this "issue" (is a usage question, not a bug report that needs action).

**Closed by hringbauer** 2023-04-12 12:39 UTC
